---
- name: Copy join to nodes
  copy:
    dest: /opt/kubejoin.sh
    src: ./join/kubejoin.sh
    mode: '0700'

- name: restart containerd
  command: sudo systemctl restart containerd

- name: Run command on remote
  shell: /opt/kubejoin.sh